# Generated by Django 2.2.28 on 2023-03-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название ингридиента', max_length=100, verbose_name='Название ингридиента')),
                ('amount', models.PositiveSmallIntegerField(help_text='Введите количество ингридиента', verbose_name='Количество ингридиента')),
                ('measurement_unit', models.CharField(help_text='Введите eдиницу измерения ингридиента', max_length=100, verbose_name='Единицы измерения ингридиента')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=100, verbose_name='Название тега')),
                ('color', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True, verbose_name='Cлаг тега')),
            ],
        ),
        migrations.CreateModel(
            name='TagRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Tag')),
            ],
        ),
    ]
