# Generated by Django 2.2.28 on 2023-03-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20230321_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Введите название рецепта', max_length=100, verbose_name='Название рецепта'),
        ),
    ]
