# Generated by Django 2.2.28 on 2023-03-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20230322_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
