# Generated by Django 2.2.28 on 2023-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20230323_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='IngredientRecipe', through='food.IngredientRecipe', to='food.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipe', through='food.TagRecipe', to='food.Tag'),
        ),
    ]
