# Generated by Django 2.2.28 on 2023-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20230323_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='food.IngredientRecipe', to='food.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='food.TagRecipe', to='food.Tag'),
        ),
    ]
