# Generated by Django 2.2.28 on 2023-03-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_auto_20230323_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_recipe_user',
        ),
    ]
