# Generated by Django 3.2.18 on 2023-03-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Нельзя на себя',
        ),
    ]
