# Generated by Django 2.2.28 on 2023-03-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230324_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscriber_user',
        ),
    ]
